name: BUILDBOT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

# ================= WINDOWS 64 =================
  build-windows-64bit:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography cffi pyinstaller

      - name: Build Windows 64bit
        run: |
          pyinstaller src/build.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dark_Souls_3_Save_Editor_WIN64
          path: dist/

# ================= WINDOWS 32 =================
  build-windows-32bit:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python (32bit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x86'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography cffi pyinstaller

      - name: Build Windows 32bit
        run: |
          pyinstaller src/build_win32.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dark_Souls_3_Save_Editor_WIN32
          path: dist/

# ================= LINUX =================
  build-linux_x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography cffi pyinstaller

      - name: Build Linux Binary
        run: |
          pyinstaller src/build.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dark_Souls_3_Save_Editor_LINUX_x86_64
          path: dist/

# ================= MAC SILICON =================
  build-macos_silicon:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography cffi pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller src/build_mac.spec

      - name: Zip App
        run: |
          cd dist
          zip -r Dark_Souls_3_Save_Editor_MAC_SILICON.zip Dark_Souls_3_Save_Editor_App.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dark_Souls_3_Save_Editor_MAC-Silicon
          path: dist/Dark_Souls_3_Save_Editor_MAC_SILICON.zip

# ================= MAC INTEL =================
  build-macos_intel:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography cffi pyinstaller

      - name: Build macOS Intel App
        run: |
          arch -x86_64 pyinstaller src/build_mac.spec

      - name: Zip App
        run: |
          cd dist
          zip -r Dark_Souls_3_Save_Editor_MAC_INTEL.zip Dark_Souls_3_Save_Editor_App.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dark_Souls_3_Save_Editor_MAC-Intel
          path: dist/Dark_Souls_3_Save_Editor_MAC_INTEL.zip
