name: BAWSDEEP  # You can change this to any name you prefer

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      # You can add more branches if needed, e.g., - develop
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_WIN'
          options: '--onefile --windowed'

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_WIN
          path: D:\a\Dark-souls-3-editor-PS4\Dark-souls-3-editor-PS4\dist\Dark_Souls_3_Save_Editor_WIN.exe  # Specified upload path

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_UNIX'
          options: '--onefile --windowed'

      - name: Upload Linux Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_UNIX
          path: /home/runner/work/Dark-souls-3-editor-PS4/Dark-souls-3-editor-PS4/dist/Dark_Souls_3_Save_Editor_UNIX  # Specified upload path