on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_WIN'
          options: '--onefile --windowed'

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_WIN
          path: D:\a\Dark-souls-3-editor-PS4\Dark-souls-3-editor-PS4\dist\Dark_Souls_3_Save_Editor_WIN.exe  # Updated path

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_UNIX'
          options: '--onefile --windowed'

      - name: Upload Linux Executable as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_UNIX
          path: /home/runner/work/Dark-souls-3-editor-PS4/Dark-souls-3-editor-PS4/dist/Dark_Souls_3_Save_Editor_UNIX  # Specified upload path

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Windows Executable Artifact
        uses: actions/download-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_WIN  # Ensure this matches the upload name

      - name: Download Linux Executable Artifact
        uses: actions/download-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_UNIX  # Updated to match the new name

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/windows/Dark_Souls_3_Save_Editor_WIN.exe  # Ensure this path is correct
            ./artifacts/linux/Dark_Souls_3_Save_Editor_UNIX  # Ensure this path is correct
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}