name: BAWSDEEP  # You can change this to any name you prefer

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows-64bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Windows Executable (64-bit)
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_WIN64'
          options: '--onefile --windowed'

  build-windows-32bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python (32-bit)
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x86'  # Specifies 32-bit Python

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create Windows Executable (32-bit)
        run: |
          pyinstaller --onefile --windowed src/build.spec
        env:
          PYTHONPATH: ${{ runner.workspace }}/src

      - name: Upload 32-Bit Executable
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_WIN32
          path: dist/Dark_Souls_3_Save_Editor.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_UNIX'
          options: '--onefile --windowed'
