name: BAWSDEEP  # You can change this to any name you prefer

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows-64bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Windows Executable (64-bit)
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_WIN64'
          options: '--onefile --windowed'

  build-windows-32bit:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python (32-bit)
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x86'  # Specifies 32-bit Python

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create Windows Executable (32-bit)
        run: |
          pyinstaller src/build.spec
        env:
          PYTHONPATH: ${{ runner.workspace }}/src

      - name: Upload 32-Bit Executable
        uses: actions/upload-artifact@v3
        with:
          name: Dark_Souls_3_Save_Editor_WIN32
          path: dist/Dark_Souls_3_Save_Editor.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'src/build.spec'
          upload_exe_with_name: 'Dark_Souls_3_Save_Editor_UNIX'
          options: '--onefile --windowed'

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install pyinstaller  # Install PyInstaller inside the virtual environment

    - name: Create macOS Executable
      run: |
        source venv/bin/activate  # Activate the virtual environment
        pyinstaller src/build_mac.spec
        # Debug the dist directory to verify output structure
        echo "Listing contents of dist/ directory:"
        ls -R dist/
      env:
        PYTHONPATH: ${{ runner.workspace }}/src

    - name: Verify .app Structure
      run: |
        # Check if the .app structure is correct
        APP_BUNDLE="dist/Dark_Souls_3_Save_Editor_App.app"
        if [ -d "$APP_BUNDLE" ]; then
          echo ".app bundle exists. Listing contents of the .app bundle:"
          ls -R "$APP_BUNDLE"
        else
          echo "Error: .app bundle not found!"
          exit 1
        fi

    - name: Upload macOS Executable
      uses: actions/upload-artifact@v3
      with:
        name: Dark_Souls_3_Save_Editor_MAC
        path: Dark_Souls_3_Save_Editor_MAC.zip